version: '3'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
      PGUSER: "${DB_USER}"
    ports:
      - "5432:5432"

  app:
    image: dafun/bot_converter_async:latest
    restart: 'no'
    volumes:
      - .:/app
      - ./migrations:/app/migrations
      - ./tables:/app/tables
    ports:
      - "9595:9595"
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A celery_app:app worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build: .
    command: celery -A celery_app:app beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker

  flower:
    build: .
    command: celery -A celery_app:app flower
    ports:
      - "5555:5555"
    depends_on:
      - worker
