"""empty message

Revision ID: 778aa7d05dc9
Revises: 
Create Date: 2023-03-11 13:00:24.090118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778aa7d05dc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('char_code', sa.String(length=200), nullable=True),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('value_updated_at', sa.DateTime(), nullable=True),
    sa.Column('ordering_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
