"""default_populate_db

Revision ID: 7e7f587603a2
Revises: a375bcce358d
Create Date: 2023-07-29 16:10:12.443048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7f587603a2'
down_revision = 'a375bcce358d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "INSERT INTO currencies (char_code, is_active, name, ordering_id, source_id, value) "
        "VALUES "
        "('BYN', False, 'Белорусский рубль', NULL, 'R01090B', '30.07'), "
        "('BGN', False, 'Болгарский лев', NULL, 'R01100', '51.75'), "
        "('BRL', False, 'Бразильский реал', NULL, 'R01115', '19.28'), "
        "('HUF', False, 'Венгерских форинтов', NULL, 'R01135', '25.98'), "
        "('VND', False, 'Вьетнамских донгов', NULL, 'R01150', '38.32'), "
        "('HKD', False, 'Гонконгский доллар', NULL, 'R01200', '11.69'), "
        "('GEL', False, 'Грузинский лари', NULL, 'R01210', '34.34'), "
        "('DKK', False, 'Датская крона', NULL, 'R01215', '13.58'), "
        "('AED', False, 'Дирхам ОАЭ', NULL, 'R01230', '24.77'), "
        "('USD', True, 'Доллар США', 2, 'R01235', '90.98'), "
        "('EUR', True, 'Евро', 3, 'R01239', '99.96'), "
        "('JPY', True, 'Японских иен', 5, 'R01820', '65.25'), "
        "('AUD', False, 'Австралийский доллар', NULL, 'R01010', '60.67'), "
        "('AZN', False, 'Азербайджанский манат', NULL, 'R01020A', '53.52'), "
        "('GBP', True, 'Фунт стерлингов Соединенного королевства', 4, 'R01035', '116.90'), "
        "('AMD', False, 'Армянских драмов', NULL, 'R01060', '23.56'), "
        "('RUB', True, 'Российский Рубль', 1, 'RUB1', '1.00'), "
        "('EGP', False, 'Египетских фунтов', NULL, 'R01240', '29.45'), "
        "('INR', False, 'Индийских рупий', NULL, 'R01270', '11.09'), "
        "('IDR', False, 'Индонезийских рупий', NULL, 'R01280', '60.64'), "
        "('KZT', False, 'Казахстанских тенге', NULL, 'R01335', '20.46'), "
        "('CAD', False, 'Канадский доллар', NULL, 'R01350', '68.92'), "
        "('QAR', False, 'Катарский риал', NULL, 'R01355', '24.99'), "
        "('KGS', False, 'Киргизских сомов', NULL, 'R01370', '10.38'), "
        "('CNY', False, 'Китайский юань', NULL, 'R01375', '12.69'), "
        "('MDL', False, 'Молдавских леев', NULL, 'R01500', '51.21'), "
        "('NZD', False, 'Новозеландский доллар', NULL, 'R01530', '56.16'), "
        "('NOK', False, 'Норвежских крон', NULL, 'R01535', '89.65'), "
        "('PLN', False, 'Польский злотый', NULL, 'R01565', '22.71'), "
        "('RON', False, 'Румынский лей', NULL, 'R01585F', '20.24'), "
        "('RUB', True, 'Российский Рубль', 1, 'RUB1', '1.00'), "
        "('XDR', False, 'СДР (специальные права заимствования)', NULL, 'R01589', '122.72'), "
        "('SGD', False, 'Сингапурский доллар', NULL, 'R01625', '68.31'), "
        "('TJS', False, 'Таджикских сомони', NULL, 'R01670', '83.31'), "
        "('THB', False, 'Таиландских батов', NULL, 'R01675', '26.71'), "
        "('TRY', False, 'Турецких лир', NULL, 'R01700J', '33.75'), "
        "('TMT', False, 'Новый туркменский манат', NULL, 'R01710A', '25.99'), "
        "('UZS', False, 'Узбекских сумов', NULL, 'R01717', '78.43'), "
        "('UAH', False, 'Украинских гривен', NULL, 'R01720', '24.63'), "
        "('CZK', False, 'Чешских крон', NULL, 'R01760', '42.08'), "
        "('SEK', False, 'Шведских крон', NULL, 'R01770', '86.04'), "
        "('CHF', False, 'Швейцарский франк', NULL, 'R01775', '104.43'), "
        "('RSD', False, 'Сербских динаров', NULL, 'R01805F', '85.16'), "
        "('ZAR', False, 'Южноафриканских рэндов', NULL, 'R01810', '50.91'), "
        "('KRW', False, 'Вон Республики Корея', NULL, 'R01815', '71.24')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
