"""empty message

Revision ID: cc3abfa4c1bb
Revises: 778aa7d05dc9
Create Date: 2023-03-12 12:37:19.085355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc3abfa4c1bb'
down_revision = '778aa7d05dc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('currencies', 'value_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('value_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('currencies', 'updated_at')
    # ### end Alembic commands ###
