name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  generate_env:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder for Generate Env
        run: echo "This is a placeholder for generating the .env file."

  deploy:
    runs-on: ubuntu-latest
    needs: generate_env
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update project and restart services
            cd /dev/bot_converter_async
            git pull origin main
            docker compose down
            docker compose up --build -d
